requires = [ "tox>=4.56.1", "tox-uv>=1.35.2" ]
env_list = [ "3.14", "3.13", "3.12", "3.11", "fix", "pkg_meta", "type" ]
skip_missing_interpreters = true

[env_run_base]
description = "run the tests with pytest under {env_name}"
package = "wheel"
wheel_build_env = ".pkg"
dependency_groups = [ "test" ]
pass_env = [ "PYTEST_*" ]
set_env.COVERAGE_FILE = { replace = "env", name = "COVERAGE_FILE", default = "{env_tmp_dir}{/}.coverage" }
set_env.COVERAGE_FILECOVERAGE_PROCESS_START = "{tox_root}{/}pyproject.toml"
commands = [
  [
    "pytest",
    { replace = "posargs", default = [
      "--no-cov-on-fail",
      "--cov",
      "{env_site_packages_dir}{/}mdformat_zola",
      "--cov",
      "{tox_root}{/}tests",
      "--cov-config",
      "{tox_root}{/}pyproject.toml",
      "--cov-context",
      "test",
      "--cov-report",
      "term-missing:skip-covered",
      "--cov-report",
      "html:{env_tmp_dir}{/}htmlcov",
      "tests",
    ], extend = true },
  ],
]

[env.fix]
description = "format the code base to adhere to our styles, and complain about what we cannot do automatically"
skip_install = true
dependency_groups = [ "lint" ]
pass_env = [
  { replace = "ref", of = [
    "env_run_base",
    "pass_env",
  ], extend = true },
  "DISABLE_PRE_COMMIT_UV_PATCH",
  "PROGRAMDATA",
]
commands = [ [ "pre-commit", "run", "--all-files", "--show-diff-on-failure", { replace = "posargs", extend = true } ] ]

[env.pkg_meta]
description = "check that the long description is valid"
skip_install = true
dependency_groups = [ "pkg-meta" ]
commands = [
  [
    "uv",
    "build",
    "--sdist",
    "--wheel",
    "--out-dir",
    "{env_tmp_dir}",
    ".",
  ],
  [
    "twine",
    "check",
    "{env_tmp_dir}{/}*",
  ],
  [
    "check-wheel-contents",
    "--no-config",
    "{env_tmp_dir}",
  ],
]

[env.type]
description = "Run Python type checker"
package = "editable"
dependency_groups = [ "type" ]
commands = [
  [
    "ty",
    "check",
    "--error",
    "all",
    "--output-format",
    "concise",
    "--error-on-warning",
    ".",
  ],
]

[env.dev]
description = "dev environment with all deps at {envdir}"
package = "editable"
dependency_groups = [ "dev" ]
commands = [
  [ "uv", "pip", "tree" ],
  [ "python", "-c", "import sys; print(sys.executable)" ],
]
